name: Build ADI artifacts

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]

env:
  BR2_DL_DIR: ~/.buildroot-dl

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        include:
          # SC598 SoM EZ-KIT builds
          - defconfig: adi_sc598_ezkit_defconfig
            name: sc598-som-ezkit-debug
            fragments: ../configs/buildroot.fragment ../configs/debug.fragment
          - defconfig: adi_sc598_ezkit_defconfig
            name: sc598-som-ezkit-bootstrap
            fragments: ../configs/buildroot.fragment ../configs/bootstrap.fragment
          # HTOL builds
          - defconfig: adi_sc598_ezkit_defconfig
            name: sc598-htol-debug
            fragments: ../configs/buildroot.fragment ../configs/htol.fragment ../configs/debug.fragment
          - defconfig: adi_sc598_ezkit_defconfig
            name: sc598-htol-bootstrap
            fragments: ../configs/buildroot.fragment ../configs/htol.fragment ../configs/bootstrap.fragment

    steps:
      - name: Checkout br2-external
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build ${{ matrix.name }}
        run: |
          cd buildroot
          make distclean
          make BR2_EXTERNAL="${PWD}/.." ${{ matrix.defconfig }}
          support/kconfig/merge_config.sh .config ${{ matrix.fragments }}
          make -j$(nproc)

      - name: Upload ${{ matrix.name }} images
        uses: actions/upload-artifact@v6
        with:
          name: images-${{ matrix.name }}
          path: buildroot/output/images

      - name: Archive output images directory
        if: ${{ github.event_name == 'release' }}
        run: |
          tar -cJvf images-${{ matrix.name }}-${{ github.event.release.tag_name }}.tar.xz \
            buildroot/output/images/

      - name: Upload release archive to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: images-${{ matrix.name }}-${{ github.event.release.tag_name }}.tar.xz
          tag: ${{ github.ref }}
