name: Build ADI artifacts

on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  schedule:
    - cron: '0 4 * * *' # 04:00 UTC (05:00/06:00 CET/CEST, 23:00/00:00 EST/EDT)

env:
  BR2_DL_DIR: ~/.buildroot-dl

jobs:
  build:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - defconfig: adi_sc598_ezkit_defconfig
            flavor: debug
          - defconfig: adi_sc598_ezkit_defconfig
            flavor: bootstrap
          - defconfig: zynq_pluto_defconfig
          - defconfig: zynq_m2k_defconfig
          - defconfig: microblaze_adi_rootfs_defconfig

    steps:
      - name: Checkout br2-external
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build image for ${{ matrix.defconfig }}${{ matrix.flavor && format(' with {0} configuration', matrix.flavor) || '' }}
        run: |
          cd buildroot
          umask 022
          make distclean
          make BR2_EXTERNAL="${PWD}/.." ${{ matrix.defconfig }}
          if [ -n "${{ matrix.flavor }}" ]; then
            support/kconfig/merge_config.sh .config \
              ../configs/buildroot.fragment \
              ../configs/${{ matrix.flavor }}.fragment
          fi
          make -j$(nproc)

      - name: Upload Buildroot images for ${{ matrix.defconfig }} with ${{ matrix.flavor }} configuration
        uses: actions/upload-artifact@v6
        with:
          name: images-${{ matrix.flavor || 'default' }}-${{ matrix.defconfig }}
          path: buildroot/output/images

      - name: Archive output images directory
        if: ${{ github.event_name == 'release' }}
        run: |
          tar -cJvf images-${{ matrix.flavor || 'default' }}-${{ matrix.defconfig }}-${{ github.event.release.tag_name }}.tar.xz \
            buildroot/output/images/

      - name: Upload release archive to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: images-${{ matrix.flavor || 'default' }}-${{ matrix.defconfig }}-${{ github.event.release.tag_name }}.tar.xz
          tag: ${{ github.ref }}
