name: Hardware Test

on:
  push:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  hardware-test:
    runs-on: ${{ vars.RUNNER_HW_TEST != '' && fromJSON(vars.RUNNER_HW_TEST) || 'ubuntu-latest' }}
    env:
      LG_COORDINATOR: ${{ secrets.LG_COORDINATOR }}

    steps:
      - name: Checkout hw-test
        uses: actions/checkout@v6
        with:
          repository: analogdevicesinc/hw-test
          ref: add-smoke3

      - name: Run smoke hardware test
        uses: ./run-test
        with:
          set: >
            {
              "name": "adsp/smoke",
              "labgrid_place":"MUN-01-SC598_EZKIT-01",
              "workflow_run_url":"https://api.github.com/repos/analogdevicesinc/br2-external/actions/runs/27766740938"
            }

      - name: Run U-Boot hardware test
        uses: ./run-test
        with:
          set: >
            {
              "name":"adsp/u-boot",
              "labgrid_place":"MUN-01-SC598_EZKIT-01",
              "workflow_run_url":"https://api.github.com/repos/analogdevicesinc/br2-external/actions/runs/27766740938"
            }

      - name: Run bootstrap hardware test
        uses: ./run-test
        with:
          set: >
            {
              "name":"adsp/bootstrap",
              "labgrid_place":"MUN-01-SC598_EZKIT-01",
              "workflow_run_url":"https://api.github.com/repos/analogdevicesinc/br2-external/actions/runs/27766740938"
            }
