name: Hardware Test

on:
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  hardware-test:
    runs-on: ${{ vars.RUNNER_HW_TEST != '' && fromJSON(vars.RUNNER_HW_TEST) || 'ubuntu-latest' }}
    env:
      LG_COORDINATOR: ${{ secrets.LG_COORDINATOR }}

    steps:
      - name: Checkout hw-test
        uses: actions/checkout@v6
        with:
          repository: analogdevicesinc/hw-test
          ref: main

      - name: Run smoke hardware test
        uses: ./run-test
        with:
          set: >
            {
              "name": "adsp/smoke"
            }

      - name: Run U-Boot hardware test
        uses: ./run-test
        with:
          set: >
            {
              "name": "adsp/u-boot"
            }

      - name: Run bootstrap hardware test
        uses: ./run-test
        with:
          set: >
            {
              "name": "adsp/bootstrap"
            }
