name: Build and Hardware Test

on:
  workflow_dispatch:
   inputs:
     skip-hw-test:
       description: "Skip hardware tests"
       default: false
       type: boolean
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-buildroot:
    strategy:
      fail-fast: false
      matrix:
        include:
          - defconfig: adi_sc598_ezkit_defconfig
            flavor: debug
          - defconfig: adi_sc598_ezkit_defconfig
            flavor: bootstrap
          - defconfig: zynq_pluto_defconfig
          - defconfig: zynq_m2k_defconfig
          - defconfig: microblaze_adi_rootfs_defconfig
    uses: ./.github/workflows/build.yml
    with:
      defconfig: ${{ matrix.defconfig }}
      flavor: ${{ matrix.flavor }}
    permissions:
      contents: write

  build-mkosi-fedora:
    uses: ./.github/workflows/fedora.yml
    permissions:
      contents: write

  hardware-test:
    uses: ./.github/workflows/hw-test.yml
    needs: [build-buildroot]
    if: ${{ !inputs.skip-hw-test && github.event_name != 'release' }}
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write

  deploy_cloudsmith:
    needs: [build-buildroot]
    if: ${{ github.event_name != 'release' && !cancelled() }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
      CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      artifacts: >
        *_defconfig*
