name: Build and Hardware Test

on:
  push:

jobs:
  hardware-test:
    uses: ./.github/workflows/hw-test.yaml
    if: ${{ github.event_name != 'schedule' && github.event_name != 'release' }}
    secrets: inherit
    permissions:
      actions: read
      contents: read
      id-token: write
